
# key: val      # yaml file requires space after colon 

augmentation: true
image_size: [224, 224, 3] 
batch_size: 16
include_top: false
epochs: 10
classes: 1
weights: imagenet
learning_rate: 0.01
freeze_all: false
freeze_till: 3
